# Generated by Django 4.2.1 on 2023-05-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='Todo',
        ),
    ]
